apiVersion: v1
kind: ConfigMap
metadata:
  name: akmebank-signature-resource
  namespace: thinkdemo
  labels:
    app.kubernetes.io/part-of: akmebank
    integrityshield.io/signatureResource: "true"
  annotations:
    argocd.interlace.dev/signature-resource: "true"
    argocd.interlace.dev/signature-compress: "true"
